# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"UnknownFormatError": "1_CocoExporter.ipynb",
         "coco_from_json": "1_CocoExporter.ipynb",
         "make_coco_metadata": "1_CocoExporter.ipynb",
         "add_label": "1_CocoExporter.ipynb",
         "append_polygons_as_annotations": "1_CocoExporter.ipynb",
         "label_to_polygons": "1_CocoExporter.ipynb",
         "LOGGER": "1_CocoExporter.ipynb",
         "root_dir": "2_LabelboxUtils.ipynb",
         "py_client": "2_LabelboxUtils.ipynb",
         "get_project": "2_LabelboxUtils.ipynb",
         "get_project_labels": "2_LabelboxUtils.ipynb",
         "get_project_coco_annotations": "2_LabelboxUtils.ipynb",
         "polygons_to_label": "2_LabelboxUtils.ipynb",
         "poly2pts": "2_LabelboxUtils.ipynb",
         "xyformat_lbl2pts": "2_LabelboxUtils.ipynb",
         "xyformat_points2label": "2_LabelboxUtils.ipynb",
         "img_from_url": "2_LabelboxUtils.ipynb",
         "bbox2sz": "2_LabelboxUtils.ipynb",
         "get_default_frontend": "2_LabelboxUtils.ipynb",
         "clone_ontology": "2_LabelboxUtils.ipynb",
         "clone_project": "2_LabelboxUtils.ipynb",
         "polyrnn_path": "3_PolygonRNN_API.ipynb",
         "device": "3_PolygonRNN_API.ipynb",
         "get_args": "3_PolygonRNN_API.ipynb",
         "get_data_loaders": "3_PolygonRNN_API.ipynb",
         "Tool": "3_PolygonRNN_API.ipynb",
         "args": "3_PolygonRNN_API.ipynb",
         "tool": "3_PolygonRNN_API.ipynb",
         "get_points": "3_PolygonRNN_API.ipynb"}

modules = ["coco_exporter.py",
           "labelbox_utils.py",
           "polygonrnn_api.py"]

git_url = "https://github.com/bearpelican/nuclei/tree/master/"

def custom_doc_links(name): return None
